/** Every command the extension registers. The manifest is checked against this list. */
export const COMMAND_IDS = [
  'betterCmm.runSetup',
  'betterCmm.copyUninstallCommand',
  'betterCmm.updateBinary',
  'betterCmm.addProject',
  'betterCmm.removeProject',
  'betterCmm.refresh',
  'betterCmm.showLogs',
  'betterCmm.showEngineLogs',
  'betterCmm.clearLog',
  'betterCmm.openSettings',
  'betterCmm.reindex',
  'betterCmm.reindexProject',
  'betterCmm.showSettings',
  'betterCmm.closeScreen',
  'betterCmm.copyBinaryDir',
  'betterCmm.setCliSetting',
  'betterCmm.copyUninstallCommandBash',
  'betterCmm.removeManagedBinary',
] as const
